spring:
  datasource:
    url: jdbc:mysql://localhost:3308/chat_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: qwer1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jwt:
    secret: ${JWT_SECRET}  # ✅ 직접 입력

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect  # 이 부분 추가!!
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  profiles:
    active: dev

  redis:
    host: localhost
    port: 6379
    timeout: 60000 # (??) ?? ???? ??

  websocket:
    enabled: true

  iamport:
    api:
      key: ${IAMPORT_API_KEY}
      secret: ${IAMPORT_API_SECRET} # ???? API Secret Key